dist: xenial
services:
- docker
matrix:
  include:
  - language: node_js
    node_js: 11
    cache: yarn
    before_script:
    - cd frontend
    - yarn install
    script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ];
      then bash ./ci/build_pull_request.sh; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ];
      then bash ./ci/build_and_deploy.sh; fi
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    env: CONTAINER_NAME=pdgwien/burgertuesday-frontend
  - language: java
    jdk: openjdk8
    before_script:
    - cd backend
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    install: true
    script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ];
      then bash ./ci/build_pull_request.sh; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ];
      then bash ./ci/build_and_deploy.sh; fi
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    env: CONTAINER_NAME=pdgwien/burgertuesday-backend
env:
  global:
  - secure: ls9+zqNpVlQ2XOwPjVvT00f2E4xeqKp8KksvdkwrPsqIn23olUNtDpaP9gGtHZa5dvV6w/ay5ZIAUP8n9Ojl9DuD1ETFtuyRXks8OUb1ICJWHpzw9ih/oogRTKvsCd6/K4FApNy93+lLL/PF14GCxM0B51crY9R0pDJrUN0EPGNihP/Z1CDDr64l0ETwffRFyjt2wZew5qsWdcXdBR8sycmcW2BfaUzxcpXZQJ4zjzaAhDJsDEJU90S3rwe3kOlp0GCj4coC/DO4n/a9GnnQ7kuGeg/o8Ru4W8z37YcBUbahQG3geoHZ5958EHmGeGfgjNMou5faLKoEMSyITkJ/o42jdNar3QoiiSzUxFxMOwNd1T7+/MYrDLMqrEXiFiUpWBdLd8PSlMxvuxkn6UzXWEXmoQ4vRuGgfD91WvZgMgqXKX8ObL43TsBzMjOx8q/HH5mrrZEq7GUw8+lWStJg0UmJz4ZPpXnk8kSNp4cQZrbWKq3iw5lM9HxC0bijF/FGtsBhYdYZn72GRuUWBC6a4FOkxc66+O1Z50eFs+OP51Vf/JwCK6Us+dz0L/BN+AXwsJrvXsfvVSdNdMvRo0gm6V3gee0Zyf62kCyMkEtLiHY0QwcClAE31jKaPrjxjvO7TbL42maxtl987wuNjJ6JttaO11Vw6sVbApTLLN4aDrE=
  - secure: pRuZARvLMCKO7tDZ1GwnLJy9LuISMdJR4sblighf3QYIcZg9Shnd2cLfPOsQU70pbHZ7lYe70im6efn6u3nKJWD90uiq3EwWIAcQfVL0yJZZw9CBiFasEVnF1q5PVCmxDLPdqrH70bAK66vnjb+AFVznYro27vHa5i1daZ31Dhc+WnzV+NiY9gXseMxNc2kKxKdCFy9dLQ1k21bXjcc5s3NAR9y/BpB1tm5/1nfgqvwPMsSkz1dOmXHK/4tGRR51h4MJh3qPiADqKwcVMcok8DnrqxpWMMsYM3yCXhZ4AOWR6tRQuoXB2SRu78AZ+pp44dp2JlTHE6ZUrZjMeHT1nON3d1SFmjvkNW9EiH6NliEJCMrGBfECYsDeSCdsxqFZQQ+NLO3J2X/YB6OAOz/F2/4j5x82jBU8UN1LWtiRMv1VAH7rrfnaDKSF0OIeyMbnV+RLBoVzOqXmcgJ5eVstcJLMUhfXwILLI80RNTq/XKtqfR7EeVDT4atnb2p1MJjw3S4ggKl+e44WgFWVAUutarRKSJTMRpxt0n48XoUqWkKG2WlOsPgFZv1yXiBS5z24f5TleD/3F1MdEGerfRgzncLEnCYT8zP0GaFbu3fZuy71DrpRfYakuukg2enGge8Wbnd3Fyff8TsE9G0BjYrLrEC9SLQggZbOTL3bIIV9AgM=
  - secure: d037WoXf0759JLcahxTv2yEL6M9OdBm1VV7dGDImLgQ/edf/kAGv0aEkFiVCKO7orYMto9GE9JOfiZEMz8TvAWQN1wyHxtSKP7YxbyKrl0O8w95Opc6l+vD6tPC6nxjM8d956W7OI3quCBDyKb8WY+TQXmIej3nV/Nto2L8FYpBeuQq8IJ8w8TVhYzq7FkevGPhN8UhNJDPPsUXESgEKs4zNO1zcU2pvUwqO2wNNZGb4sQ8ey/VfNpkPEW3Tnt1MmnmlEXHMc7jb3JyM8Nt7sgDUdjE7VxZkUiRYo5Md04G4V0NoI4Jdb8VD1dcRsl1tRjwq1Jmqn2eS/4T3l6WMK8XoCJv9Oa8LmFIfIRw3L15sUnVlTTx/1FYfysZEleCthF3VBy7OccQuaOOP+Rhghbp+kd2koOAs7Fib1zPz7M6oEGBy5Grw5DbL8EsIPqqk4FUPm0zq1sx5GaPG/61tBKJqVI0ubrEOifxFfaiQ3PeU5M6drFSmwqJ8T/86iXd1j8X32p9tmfAqSNBMIDdO0pLhOWubvSiGwOc3PzQ31CNIil3Xoz0YucMT8kup3A1Ll3KsCrxELq4IOZh8QnZqa/h2tiWzDwHXYamQD/YUR4PVavikvGmuCYYRLJac8O7fS8c1qhKEcnn201uk5QO5Be6UprrXG0GmH4LXPGWlxWs=
notifications:
  webhooks:
  - https://hooks.microbadger.com/images/pdgwien/burgertuesday-backend/XWc0gT7MJ5aqpwiV_-e5qic_A8Q=
  - https://hooks.microbadger.com/images/pdgwien/burgertuesday-frontend/z1scdZp9B5WqhyDP3Xuk21t4_TE=
