spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bt
    username: admin
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
