spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db
    username: admin
    password:
application:
  auth0:
    audience: https://burgertuesday.rocks
    issuer: https://burgertuesday.eu.auth0.com/
logging.level.org.springframework.web: DEBUG
