spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db
    username: admin
    password:
auth0:
  issuer: https://burgertuesday.eu.auth0.com/
  apiAudience: https://burgertuesday.rocks
logging.level.org.springframework.web: DEBUG

