spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      generate_statistics: true
  http:
    log-request-details: true
application:
  auth0:
    audience: https://burgertuesday.rocks
    issuer: https://burgertuesday.eu.auth0.com/
  google:
    apiKey: ${GOOGLE_API_KEY:false}
  idMask:
    secret: ${ID_MASK_SECRET:false}
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate.stat: DEBUG
